### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by davidchalifoux** [raydog/adventure.js#2]
Hey @raydog , thanks for making this wonderful port!
I'm currently using it for my project: https://github.com/davidchalifoux/adventure

Because `gameUtils` uses the Node.js crypto library, this does not work when running in the browser. https://github.com/raydog/adventure.js/blob/c96efa9f815d98e8e9e8c83feab74c443a13bdb0/src/gameUtils.js#L19 

I quickly made a working fork of this that does work in the browser. However, I feel like it doesn't warrant a whole separate fork.
https://github.com/davidchalifoux/adventure.js-web/blob/master/src/gameUtils.js

Thoughts? Should I clean it up and make a PR?

**Comment by raydog** [comment]
Hey @davidchalifoux. Glad to hear that this old project was useful to you. :slightly_smiling_face: 

You raise a good point about the crypto library; it does make use in the browser a bit more tricky. I had only really considered the server use-case, simply because this project was originally a slackbot.

I checked out your fork. The solution you arrived at (creating a fallback for when crypto isn't available) would be good if we truly needed the game's RNG seed to be cryptographically safe. However, we don't _really_ need that, and so a simpler solution would be to just not seed it at all, since [the mersenne-twister library will seed itself using the current time](https://github.com/boo1ean/mersenne-twister/blob/bdb5bd16d571c527d88ec29262ac3dde13798da7/src/mersenne-twister.js#L68-L70) if nothing is passed in to the constructor.

I just pushed a small commit to simplify the seed logic, and remove crypto. Tell me if 23f530aa3e8c685512462a3b36634a4fca058715 works for you.

**Comment by davidchalifoux** [comment]
Thanks for taking the time to push that @raydog! 
I definitely agree that the seed doesn't need to be perfect. I was unsure of what you preferred which is why I went that route.

I tested it locally and it worked without any issues! Could you push this update to NPM?

**Comment by raydog** [comment]
Published as [1.0.1](https://www.npmjs.com/package/adventurejs/v/1.0.1)
